In [2]:
import torch
import numpy as np

## 1.  Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):


* See the documentation on `torch.Tensor`

* See the documentation on `torch.cuda`

## 2. Create a random tensor with shape (7, 7)

In [4]:
ran_tensor = torch.rand(7,7)
ran_tensor, ran_tensor.shape

(tensor([[0.2981, 0.2419, 0.3006, 0.4658, 0.5118, 0.9624, 0.0333],
         [0.0330, 0.4224, 0.5189, 0.7356, 0.5381, 0.6921, 0.4628],
         [0.7215, 0.8018, 0.1373, 0.8347, 0.2964, 0.9185, 0.2824],
         [0.4526, 0.5875, 0.9398, 0.6742, 0.3791, 0.4473, 0.3314],
         [0.9226, 0.1968, 0.3355, 0.0170, 0.6962, 0.3456, 0.0419],
         [0.3795, 0.1322, 0.5951, 0.4133, 0.9203, 0.7678, 0.9571],
         [0.2072, 0.8388, 0.7778, 0.9810, 0.1635, 0.5066, 0.7898]]),
 torch.Size([7, 7]))

## 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [5]:
ran_tensorA = torch.rand(7,7)
ran_tensorB = torch.rand(1,7).T
print(ran_tensorA)
print(ran_tensorB)
print(ran_tensorA.shape, ran_tensorB.shape)

tensor([[0.6304, 0.9553, 0.7191, 0.4545, 0.5826, 0.1485, 0.0223],
        [0.6729, 0.8130, 0.7943, 0.2747, 0.5244, 0.3534, 0.6756],
        [0.1795, 0.3559, 0.3411, 0.4103, 0.6086, 0.5703, 0.8986],
        [0.9309, 0.2027, 0.4362, 0.6522, 0.6761, 0.1278, 0.9282],
        [0.0586, 0.0289, 0.0847, 0.0222, 0.1789, 0.8973, 0.7566],
        [0.8166, 0.9615, 0.6791, 0.8991, 0.7632, 0.6940, 0.9013],
        [0.0848, 0.7251, 0.5044, 0.3086, 0.8016, 0.6541, 0.5445]])
tensor([[0.2720],
        [0.8312],
        [0.4195],
        [0.0264],
        [0.7774],
        [0.1020],
        [0.2588]])
torch.Size([7, 7]) torch.Size([7, 1])


What would be the result size? A tensor with shape 7 rows (1st matrix) and 1 column (2nd matrix).

In [6]:
torch.matmul(ran_tensorA, ran_tensorB)

tensor([[1.7530],
        [1.8178],
        [1.2624],
        [1.4007],
        [0.5025],
        [2.2272],
        [1.6763]])

## 4. Set the random seed to 0 and do exercises 2 & 3 over again.



In [7]:
# Set random seed
RANDOM_SEED = 42

# Apply random seed to tensor A
torch.manual_seed(RANDOM_SEED)
ran_tensorA = torch.rand(7,7)

# Apply random seed to tensor B
torch.manual_seed(RANDOM_SEED)
ran_tensorB = torch.rand(1,7).T

print(ran_tensorA)
print(ran_tensorB)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])
tensor([[0.8823],
        [0.9150],
        [0.3829],
        [0.9593],
        [0.3904],
        [0.6009],
        [0.2566]])


In [8]:
# Perform matrix multiplication
torch.matmul(ran_tensorA, ran_tensorB)

tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])

## 5. Speaking of random seeds, we saw how to set it with ` torch.manual_seed() ` but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [24]:
# Set the random seed
RANDOM_SEED = 1234

# At this point, I changed to Google Colab GPU T4
print(torch.cuda.is_available())

# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available()else 'cpu'

# Move tensor to GPU (if available)
tensor = tensor.to(device)

# Apply random seed
torch.manual_seed(RANDOM_SEED)

True


## 6. Create two random tensors of shape `(2, 3)`and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)

In [32]:
# Set the random seed
RANDOM_SEED = 1234

# Apply random seed to tensor A
torch.manual_seed(RANDOM_SEED)

# Send tensor A to GPU
tensorA = torch.rand(2,3).to(device)

# Apply random seed to tensor A
torch.manual_seed(RANDOM_SEED)

# Send tensor A to GPU
tensorB = torch.rand(2,3).to(device)

tensorA,tensorB

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

## 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [35]:
print(tensorA.shape, tensorB.shape)

torch.Size([2, 3]) torch.Size([2, 3])


In [56]:
tensorBT = tensorB.T
print(tensorAT.shape, tensorB.shape)

torch.Size([3, 2]) torch.Size([2, 3])


In [57]:
tensor_mult = torch.matmul(tensorA, tensorBT)
tensor_mult

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

## 8. Find the maximum and minimum values of the output of 7.

In [58]:
# Minimum value
print(f'Minimum value: {tensor_mult.min()}')

# Maximum value
print(f'Maximum value: {tensor_mult.max()}')

Minimum value: 0.21611443161964417
Maximum value: 0.628727912902832


## 9.Find the maximum and minimum index values of the output of 7.

In [59]:
# Print tensor
print(tensor_mult)

# Minimum index value
print(f'\nMinimum index value: {tensor_mult.argmin()}\n')

# Maximum index value
print(f'Maximum index value: {tensor_mult.argmax()}\n')

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

Minimum index value: 1

Maximum index value: 3



# 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [70]:
# Create random seed
torch.manual_seed(7)

# Create a random tensor
rand_tensor = torch.rand(1,1,1,10)
print(rand_tensor, rand_tensor.shape)

# Remove all the 1 dimensions
removed_rand_tensor = rand_tensor.squeeze()
print('\n',removed_rand_tensor,removed_rand_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])

 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
